name: animation_practice
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  simple_animations: ^5.0.0+3
  supercharged: ^2.1.1
  transparent_image: ^2.0.1
  intl: ^0.18.1
  confetti: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  lint: ^2.1.2

flutter_gen:
  output: lib/assets/
  line_length: 80

flutter:
  uses-material-design: true
  assets:
    - assets/
